#!/bin/env bash

# Compile instructions for ATTiny45
avr-gcc -mmcu=attiny45 -DF_CPU=1234567Lu shiftled.c -o shiftled.o
avr-objcopy -j .text -j .data -O ihex shiftled.o shiftled.hex

# Write to the flash on the ATTiny45
sudo avrdude -c usbtiny -p t45 -U flash:w:shiftled.hex

# Clean up object file
rm shiftled.o
