#!/bin/env bash

# Compile instructions for ATTiny45
avr-gcc -mmcu=attiny45 -DF_CPU=1234567Lu testled.c -o testled.o
avr-objcopy -j .text -j .data -O ihex testled.o testled.hex

# Write to the flash on the ATTiny45
sudo avrdude -c usbtiny -p t45 -U flash:w:testled.hex

# Clean up object file
rm testled.o
